name: llm-judge
channels:
  - conda-forge
  - defaults
dependencies:
  # Python version
  - python=3.11

  # Core data science libraries
  - pandas>=2.0.0
  - numpy>=1.24.0
  - scikit-learn>=1.3.0

  # Interactive tool building
  - streamlit
  
  # Visualization
  - matplotlib>=3.7.0
  - seaborn>=0.12.0

  # Configuration and file handling
  - tomli>=2.0.0  # For Python <3.11 compatibility (tomllib is built-in for 3.11+)
  - toml>=0.10.2  # or just use the oldschool toml

  # Development and utilities
  - jupyter
  - ipython
  - pytest
  - black
  - flake8
  - isort

  # Optional: if you want to include these via conda
  - requests
  - urllib3

  # Pip-only dependencies
  - pip
  - pip:
    - openai>=1.0.0
    - tqdm>=4.65.0  # Progress bars for batch processing
    - rich>=13.0.0  # Enhanced terminal output

# Additional channels for specialized packages
# channels:
#   - pytorch  # Uncomment if you need PyTorch for advanced NLP
#   - huggingface  # Uncomment if you need Transformers library


# To create environment:
# conda env create -f environment.yml

# To activate:
# conda activate conversation-manager

# To update the environment with changes from environment.yml:
# conda env update --file environment.yml --name conversation-manager

# To stop:
# conda deactivate

# Delete the environment 
# conda remove --name conversation-manager --all